name: Build Electron App fro macOS and windows

on:
  push:
    branches: [main]

jobs:
  check-node-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Node_ENV from package.json
        id: nove_env
        run: echo "NODE_ENV=$(node -p "require('./package.json').env.NODE_ENV")" >> $GITHUB_ENV

      - name: Verify NODE_ENV
        run: |
          if [ "$NODE_ENV" != "production" ]; then
            echo "NODE_ENV is not production. Skipping build."
              exit 1
                fi

  build-mac:
    needs: check-node-env
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Set up GH_TOKEN
        run: echo "GH_TOKEN = ${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the app for macOS
        run: npm run dist:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload mac artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Xing-scraper-mac
          path: dist/*.dmg

      - name: Publish Mac Update
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-windows:
    needs: check-node-env
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Set up GH_TOKEN
        run: echo "GH_TOKEN = ${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the app for windows
        run: npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload windows 64-bit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Xing-scraper-windows
          path: dist/*.exe

      - name: Publish Windows Update
        run: npm run publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
